fixed bug of codeblock without subTitle
```
Failures:

  1) TDiary::Style::GfmDiary codeblock without subTitle
     Failure/Error: section << l

     NoMethodError:
       undefined method `<<' for nil:NilClass
     # ./lib/tdiary/style/gfm.rb:180:in `block in append'
     # ./lib/tdiary/style/gfm.rb:169:in `each_line'
     # ./lib/tdiary/style/gfm.rb:169:in `append'
     # ./spec/tdiary/style/gfm_spec.rb:619:in `block (3 levels) in <top (required)>'
```